code = "WF.2.4"
competency_code = "WF.2"
descriptor = "Celebration of Learning"
statement = "I willingly participate in Celebration of Learning events by exhibiting my learning as well as artifacts I create."

[evidence_required]
9 = 0
10 = 1
11 = 0
12 = 0
default = 1
