code = "WF.2.5"
competency_code = "WF.2"
descriptor = "Foundations Capstone"
statement = "I can present a plan for my design years to a panel of adults and peers by communicating my academic progress, personal growth, and best work"

[evidence_required]
9 = 0
10 = 1
11 = 0
12 = 0
default = 1
