code = "WL.3.1"
competency_code = "WL.3"
descriptor = "Compare the Language Studied and Your Own"
statement = "How do I compare the language studied to my own?"

[evidence_required]
9 = 2
10 = 2
11 = 0
12 = 0
default = 1
