code = "MS.HSN-VM.B.4.B"
competency_code = "MS.HSN"
descriptor = "VM.B.4.B Perform operations on vectors."
statement = "Given two vectors in magnitude and direction form, determine the magnitude and direction of their sum."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
