code = "MS.HSN-Q.A.1"
competency_code = "MS.HSN"
descriptor = "Q.A.1 Reason quantitatively and use units to solve problems."
statement = "Use units as a way to understand problems and to guide the solution of multi-step problems; choose and interpret units consistently in formulas; choose and interpret the scale and the origin in graphs and data displays."

[evidence_required]
9 = 0
10 = 0
11 = 4
12 = 0
default = 1
