code = "MS.HSN-CN.A.3"
competency_code = "MS.HSN"
descriptor = "CN.A.3 Perform arithmetic operations with complex numbers."
statement = "Find the conjugate of a complex number; use conjugates to find moduli and quotients of complex numbers."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
