code = "MS.HSN-RN.A.1"
competency_code = "MS.HSN"
descriptor = "RN.A.1 Extend the properties of exponents to rational exponents."
statement = "Explain how the definition of the meaning of rational exponents follows from extending the properties of integer exponents to those values, allowing for a notation for radicals in terms of rational exponents. For example, we define 5^(1/3) to be the cube root of 5 because we want [5^(1/3)]^3 = 5^[(1/3) x 3] to hold, so [5^(1/3)]^3 must equal 5."

[evidence_required]
9 = 0
10 = 1
11 = 0
12 = 0
default = 1
