code = "MS.HSN-VM.A.3"
competency_code = "MS.HSN"
descriptor = "VM.A.3 Represent and model with vector quantities."
statement = "Solve problems involving velocity and other quantities that can be represented by vectors."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
