code = "MS.HSN-VM.B.5.B"
competency_code = "MS.HSN"
descriptor = "VM.B.5.B Perform operations on vectors."
statement = "Compute the magnitude of a scalar multiple cv using ||cv|| = |c|v. Compute the direction of cv knowing that when |c|v =? 0, the direction of cv is either along v (for c > 0) or against v (for c < 0)."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
