code = "MS.HSN-RN.B.3"
competency_code = "MS.HSN"
descriptor = "RN.B.3 Use properties of rational and irrational numbers."
statement = "Explain why the sum or product of rational numbers is rational; that the sum of a rational number and an irrational number is irrational; and that the product of a nonzero rational number and an irrational number is irrational."

[evidence_required]
9 = 1
10 = 0
11 = 0
12 = 0
default = 1
