code = "MS.HSN-CN.B.5"
competency_code = "MS.HSN"
descriptor = """
CN.B.5 Represent complex numbers and their operations on the complex
 plane."""
statement = "Represent addition, subtraction, multiplication, and conjugation of complex numbers geometrically on the complex plane; use properties of this representation for computation. For example, (-1 ± ?3i)^3 = 8 because (-1 ±?3i) has modulus 2 and argument 120°."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
