code = "MS.HSN-CN.C.8"
competency_code = "MS.HSN"
descriptor = "CN.C.8 Use complex numbers in polynomial identities and equations."
statement = "Extend polynomial identities to the complex numbers. For example, rewrite x^2 + 4 as (x + 2i)(x - 2i)."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
