code = "WL.1.1"
competency_code = "WL.1"
descriptor = "Engage in Conversations"
statement = "How well can I participate in conversations to negotiate and share information?"

[evidence_required]
9 = 4
10 = 4
11 = 0
12 = 0
default = 1
