code = "WL.1.4"
competency_code = "WL.1"
descriptor = "Interpret Spoken Language"
statement = "How well can I understand and interpret what I hear?"

[evidence_required]
9 = 4
10 = 4
11 = 0
12 = 0
default = 1
