code = "WL.1"
competency_area_code = "WL"
descriptor = "Communicate in Languages Other Than English"
statement = "I can communicate effectively in more than one language in order to function in a variety of situations and for multiple purposes."
