code = "WL.3"
competency_area_code = "WL"
descriptor = "Develop Insight into the Nature of Language and Culture"
statement = "I can develop insight into the nature language and culture in order to interact with cultural competence."
