code = "MS.HSG-CO.B.7"
competency_code = "MS.HSG"
descriptor = "CO.B.7 Understand congruence in terms of rigid motions"
statement = "Use the definition of congruence in terms of rigid motions to show that two triangles are congruent if and only if corresponding pairs of sides and corresponding pairs of angles are congruent."

[evidence_required]
9 = 0
10 = 0
11 = 1
12 = 0
default = 1
