code = "MS.HSG-SRT.A.1.B"
competency_code = "MS.HSG"
descriptor = "SRT.A.1.B Understand similarity in terms of similarity transformations"
statement = "The dilation of a line segment is longer or shorter in the ratio given by the scale factor."

[evidence_required]
9 = 0
10 = 0
11 = 1
12 = 0
default = 1
