code = "MS.HSG-SRT.B.5"
competency_code = "MS.HSG"
descriptor = "SRT.B.5 Prove theorems involving similarity"
statement = "Use congruence and similarity criteria for triangles to solve problems and to prove relationships in geometric figures."

[evidence_required]
9 = 0
10 = 0
11 = 4
12 = 0
default = 1
