code = "MS.HSG-SRT.B.4"
competency_code = "MS.HSG"
descriptor = "SRT.B.4 Prove theorems involving similarity"
statement = "Prove theorems about triangles. Theorems include: a line parallel to one side of a triangle divides the other two proportionally, and conversely; the Pythagorean Theorem proved using triangle similarity."

[evidence_required]
9 = 0
10 = 0
11 = 1
12 = 0
default = 1
