code = "MS.HSG-CO.A.5"
competency_code = "MS.HSG"
descriptor = "CO.A.5 Experiment with transformations in the plane"
statement = "Given a geometric figure and a rotation, reflection, or translation, draw the transformed figure using, e.g., graph paper, tracing paper, or geometry software. Specify a sequence of transformations that will carry a given figure onto another."

[evidence_required]
9 = 0
10 = 0
11 = 2
12 = 0
default = 1
