code = "MS.HSG-CO.A.1"
competency_code = "MS.HSG"
descriptor = "CO.A.1 Experiment with transformations in the plane"
statement = "Know precise definitions of angle, circle, perpendicular line, parallel line, and line segment, based on the undefined notions of point, line, distance along a line, and distance around a circular arc."

[evidence_required]
9 = 0
10 = 0
11 = 1
12 = 0
default = 1
