code = "MS.HSG-GMD.A.1"
competency_code = "MS.HSG"
descriptor = "GMD.A.1 Explain volume formulas and use them to solve problems"
statement = "Give an informal argument for the formulas for the circumference of a circle, area of a circle, volume of a cylinder, pyramid, and cone. Use dissection arguments, Cavalieri's principle, and informal limit arguments."

[evidence_required]
9 = 0
10 = 0
11 = 1
12 = 0
default = 1
