code = "MS.HSG-GPE.B.5"
competency_code = "MS.HSG"
descriptor = "GPE.B.5 Use coordinates to prove simple geometric theorems algebraically"
statement = "Prove the slope criteria for parallel and perpendicular lines and use them to solve geometric problems (e.g., find the equation of a line parallel or perpendicular to a given line that passes through a given point)."

[evidence_required]
9 = 0
10 = 0
11 = 1
12 = 0
default = 1
