code = "VA.3.2"
competency_code = "VA.3"
descriptor = "Use criteria to critique artwork"
statement = "How well do I use criteria to critique artwork?"

[evidence_required]
9 = 1
10 = 1
11 = 2
12 = 2
default = 1
