code = "SCI.3"
competency_area_code = "SCI"
descriptor = "Develop and Use Models"
statement = "I can develop and use models to make predictions about phenomena, analyze systems, and communicate ideas."
