code = "PE.2"
competency_area_code = "PE"
descriptor = "Demonstrate Personal and Social Skills"
statement = "Demonstrate and explain responsible personal behavior and responsible social behavior in physical activity settings."
