code = "PE.3"
competency_area_code = "PE"
descriptor = "Advance Health and Movement Performance"
statement = "Demonstrate the fundamental and specialized motor skills and apply principles of movement for improved performance and health."
