code = "WL.2.2"
competency_code = "WL.2"
descriptor = "Relate Cultural Products to Perspectives"
statement = "How do I analyze products and perspectives?"

[evidence_required]
9 = 2
10 = 2
11 = 0
12 = 0
default = 1
