code = "WL.2.1"
competency_code = "WL.2"
descriptor = "Relate Cultural Practices to Perspectives"
statement = "How do I analyze practices and perspectives?"

[evidence_required]
9 = 2
10 = 2
11 = 0
12 = 0
default = 1
