code = "WF.4.5"
competency_code = "WF.4"
descriptor = "Design Capstone"
statement = "I can identify a problem, issue, or challenge I am passionate about and then create and implement my solution in the world."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 1
default = 1
