code = "ELA.7.1"
competency_code = "ELA.7"
descriptor = "Construct a research question"
statement = "How well do I construct my primary question?"

[evidence_required]
9 = 1
10 = 2
11 = 3
12 = 2
default = 1
