code = "MS.HSS-ID.C.8"
competency_code = "MS.HSS"
descriptor = "ID.C.8 Interpret linear models"
statement = "Compute (using technology) and interpret the correlation coefficient of a linear fit"

[evidence_required]
9 = 1
10 = 0
11 = 0
12 = 0
default = 1
