code = "MS.HSS-CP.A.3"
competency_code = "MS.HSS"
descriptor = "CP.A.3 Understand independence and conditional probability and use them to interpret data"
statement = "Understand the conditional probability of A given B as P(A and B)/P(B), and interpret independence of A and B as saying that the conditional probability of A given B is the same as the probability of A, and the conditional probability of B given A is the same as the probability of B."

[evidence_required]
9 = 0
10 = 0
11 = 1
12 = 0
default = 1
