code = "MS.HSS-ID.C.9"
competency_code = "MS.HSS"
descriptor = "ID.C.9 Interpret linear models"
statement = "Distinguish between correlation and causation"

[evidence_required]
9 = 1
10 = 0
11 = 0
12 = 0
default = 1
