code = "MS.HSS-MD.B.7"
competency_code = "MS.HSS"
descriptor = "MD.B.7 Use probability to evaluate outcomes of decisions"
statement = "Analyze decisions and strategies using probability concepts (e.g., product testing, medical testing, pulling a hockey goalie at the end of a game)."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
