code = "MS.HSS-MD.A.4"
competency_code = "MS.HSS"
descriptor = "MD.A.4 Calculate expected values and use them to solve problems"
statement = "Develop a probability distribution for a random variable defined for a sample space in which probabilities are assigned empirically; find the expected value. For example, find a current data distribution on the number of TV sets per household in the United States, and calculate the expected number of sets per household. How many T V sets would you expect to find in 100 randomly selected households?"

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
