code = "MS.HSS-MD.A.2"
competency_code = "MS.HSS"
descriptor = "MD.A.2 Calculate expected values and use them to solve problems"
statement = "Calculate the expected value of a random variable; interpret it as the mean of the probability distribution."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
