code = "MS.HSS-CP.A.4"
competency_code = "MS.HSS"
descriptor = "CP.A.4 Understand independence and conditional probability and use them to interpret data"
statement = "Construct and interpret two-way frequency tables of data when two categories are associated with each object being classified. Use the two-way table as a sample space to decide if events are independent and to approximate conditional probabilities. For example, collect data from a random sample of students in your school on their favorite subject among math, science, and English. Estimate the probability that a randomly selected student from your school will favor science given that the student is in tenth grade. Do the same for other subjects and compare the results."

[evidence_required]
9 = 0
10 = 0
11 = 1
12 = 0
default = 1
