code = "MS.HSS-ID.B.6.A"
competency_code = "MS.HSS"
descriptor = "ID.B.6.A Summarize, represent, and interpret data on two categorical and quantitative variables"
statement = "Fit a function to the data; use functions fitted to data to solve problems in the context of the data. Use given functions or choose a function suggested by the context. Emphasize linear, quadratic, and exponential models."

[evidence_required]
9 = 1
10 = 2
11 = 0
12 = 0
default = 1
