code = "MS.HSS-ID.B.6"
competency_code = "MS.HSS"
descriptor = "ID.B.6 Summarize, represent, and interpret data on two categorical and quantitative variables"
statement = "Represent data on two quantitative variables on a scatter plot, and describe how the variables are related."

[evidence_required]
9 = 0
10 = 1
11 = 0
12 = 0
default = 1
