code = "MS.HSS-MD.B.6"
competency_code = "MS.HSS"
descriptor = "MD.B.6 Use probability to evaluate outcomes of decisions"
statement = "Use probabilities to make fair decisions (e.g., drawing by lots, using a random number generator)."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
