code = "MS.HSS-CP.A.1"
competency_code = "MS.HSS"
descriptor = "CP.A.1 Understand independence and conditional probability and use them to interpret data"
statement = 'Describe events as subsets of a sample space (the set of outcomes) using characteristics (or categories) of the outcomes, or as unions, intersections, or complements of other events ("or," "and," "not").'

[evidence_required]
9 = 0
10 = 0
11 = 3
12 = 0
default = 1
