code = "PE.2.1"
competency_code = "PE.2"
descriptor = "Demonstrate collaboration skills during physical activities"
statement = "I can demonstrate key collaborative skills while participating in physical activities, such as giving and accepting constructive feedback, and ensuring respectful inclusion of peers in activities."

[evidence_required]
9 = 0
10 = 4
11 = 0
12 = 0
default = 1
