code = "ELA.6.2"
competency_code = "ELA.6"
descriptor = "Pose and respond to questions"
statement = "How well do I pose and respond to questions?"

[evidence_required]
9 = 2
10 = 3
11 = 4
12 = 3
default = 1
