code = "HOS.2.1"
competency_code = "HOS.2"
descriptor = "Monitor and manage my learning"
statement = "How well do I use my competency dashboard and my PLP to monitor my progress?"

[evidence_required]
9 = 4
10 = 4
11 = 4
12 = 4
default = 1
