code = "HW.1"
competency_area_code = "HW"
descriptor = "Apply Knowledge of Health Concepts"
statement = "I can apply knowledge of concepts related to health promotion and disease prevention to enhance my health."
