code = "HW.2"
competency_area_code = "HW"
descriptor = "Analyze Health Promotion and Risk Reduction"
statement = "I can demonstrate the ability to practice health-enhancing behaviors and avoid or reduce health risks."
