code = "HW.3"
competency_area_code = "HW"
descriptor = "Engage in Health Advocacy"
statement = "I can demonstrate the ability to use interpersonal communication and advocacy skills; make decisions; and set goals to enhance my personal, family and community health."
