code = "VA.2.3"
competency_code = "VA.2"
descriptor = "Convey meaning through the presentation of artistic work"
statement = "How well do I coney a larger meaning through my presentation of artistic work?"

[evidence_required]
9 = 1
10 = 1
11 = 2
12 = 2
default = 1
