code = "MATH.1"
competency_area_code = "MATH"
descriptor = "Mathematical Problem Solving"
statement = "I can apply mathematical problem solving strategies to create efficient and high quality solutions to challenging problems."
