code = "MATH.2"
competency_area_code = "MATH"
descriptor = "Mathematical Argumentation and Reflection"
statement = "I can build, defend, and critique mathematical arguments while reflecting on my own problem solving processes and solutions."
