code = "MS.HSF-TF.A.4"
competency_code = "MS.HSF"
descriptor = "TF.A.4 Extend the domain of trigonometric functions using the unit circle"
statement = "Use the unit circle to explain symmetry (odd and even) and periodicity of trigonometric functions."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
