code = "MS.HSF-IF.C.9"
competency_code = "MS.HSF"
descriptor = "IF.C.9 Analyze functions using different representations"
statement = "Compare properties of two functions each represented in a different way (algebraically, graphically, numerically in tables, or by verbal descriptions). For example, given a graph of one quadratic function and an algebraic expression for another, say which has the larger maximum."

[evidence_required]
9 = 1
10 = 1
11 = 0
12 = 0
default = 1
