code = "MS.HSF-BF.A.1"
competency_code = "MS.HSF"
descriptor = "BF.A.1 Build a function that models a relationship between two quantities"
statement = "Write a function that describes a relationship between two quantities."

[evidence_required]
9 = 1
10 = 3
11 = 0
12 = 0
default = 1
