code = "MS.HSF-BF.B.4.C"
competency_code = "MS.HSF"
descriptor = "BF.B.4.C Build new functions from existing functions"
statement = "Read values of an inverse function from a graph or a table, given that the function has an inverse."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
