code = "MS.HSF-TF.B.7"
competency_code = "MS.HSF"
descriptor = "TF.B.7 Model periodic phenomena with trigonometric functions"
statement = "Use inverse functions to solve trigonometric equations that arise in modeling contexts; evaluate the solutions using technology, and interpret them in terms of the context.*"

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
