code = "MS.HSF-TF.C.8"
competency_code = "MS.HSF"
descriptor = "TF.C.8 Prove and apply trigonometric identities"
statement = "Prove the Pythagorean identity (sin A)^2 + (cos A)^2 = 1 and use it to calculate trigonometric ratios."

[evidence_required]
9 = 0
10 = 1
11 = 0
12 = 0
default = 1
