code = "MS.HSF-IF.C.7.C"
competency_code = "MS.HSF"
descriptor = "IF.C.7.C Analyze functions using different representations"
statement = "Graph polynomial functions, identifying zeros when suitable factorizations are available, and showing end behavior."

[evidence_required]
9 = 0
10 = 1
11 = 0
12 = 0
default = 1
