code = "MS.HSF-BF.B.4.A"
competency_code = "MS.HSF"
descriptor = "BF.B.4.A Build new functions from existing functions"
statement = "Solve an equation of the form f(x) = c for a simple function f that has an inverse and write an expression for the inverse. For example, f(x) =2(x^3) for x > 0 or f(x) = (x+1)/(x-1) for x =? 1 (x not equal to 1). "

[evidence_required]
9 = 1
10 = 0
11 = 0
12 = 0
default = 1
