code = "MS.HSF-BF.B.4.B"
competency_code = "MS.HSF"
descriptor = "BF.B.4.B Build new functions from existing functions"
statement = "Verify by composition that one function is the inverse of another."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
