code = "MS.HSF-TF.A.2"
competency_code = "MS.HSF"
descriptor = "TF.A.2 Extend the domain of trigonometric functions using the unit circle"
statement = "Explain how the unit circle in the coordinate plane enables the extension of trigonometric functions to all real numbers, interpreted as radian measures of angles traversed counterclockwise around the unit circle."

[evidence_required]
9 = 0
10 = 1
11 = 0
12 = 0
default = 1
