code = "MS.HSF-BF.A.2"
competency_code = "MS.HSF"
descriptor = "BF.A.2 Build a function that models a relationship between two quantities"
statement = "Write arithmetic and geometric sequences both recursively and with an explicit formula, use them to model situations, and translate between the two forms.*"

[evidence_required]
9 = 0
10 = 1
11 = 0
12 = 0
default = 1
