code = "MS.HSF-IF.A.2"
competency_code = "MS.HSF"
descriptor = "IF.A.2 Understand the concept of a function and use function notation"
statement = "Use function notation, evaluate functions for inputs in their domains, and interpret statements that use function notation in terms of a context."

[evidence_required]
9 = 2
10 = 0
11 = 0
12 = 0
default = 1
