code = "MS.HSF-BF.B.4.D"
competency_code = "MS.HSF"
descriptor = "BF.B.4.D Build new functions from existing functions"
statement = "Produce an invertible function from a non-invertible function by restricting the domain."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
