code = "MS.HSF-IF.B.4"
competency_code = "MS.HSF"
descriptor = "IF.B.4 Interpret functions that arise in applications in terms of the context"
statement = "For a function that models a relationship between two quantities, interpret key features of graphs and tables in terms of the quantities, and sketch graphs showing key features given a verbal description of the relationship. Key features include: intercepts; intervals where the function is increasing, decreasing, positive, or negative; relative maximums and minimums; symmetries; end behavior; and periodicity.*"

[evidence_required]
9 = 4
10 = 3
11 = 0
12 = 0
default = 1
