code = "MS.HSF-IF.C.8"
competency_code = "MS.HSF"
descriptor = "IF.C.8 Analyze functions using different representations"
statement = "Write a function defined by an expression in different but equivalent forms to reveal and explain different properties of the function. "

[evidence_required]
9 = 1
10 = 0
11 = 0
12 = 0
default = 1
