code = "MS.HSF-TF.B.6"
competency_code = "MS.HSF"
descriptor = "TF.B.6 Model periodic phenomena with trigonometric functions"
statement = "Understand that restricting a trigonometric function to a domain on which it is always increasing or always decreasing allows its inverse to be constructed."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
