code = "PE.3.2"
competency_code = "PE.3"
descriptor = "Develop and strengthen motor skills"
statement = "I can incorporate and synthesize knowledge of motor skill development concepts to improve the quality of motor skills."

[evidence_required]
9 = 0
10 = 4
11 = 0
12 = 0
default = 1
