code = "PE.3.3"
competency_code = "PE.3"
descriptor = "Apply knowledge of the impacts of exercise"
statement = "I can apply my knowledge of the interaction between the type and duration of exercise and their effects on the body to make informed choices about physical activities and exercise regimens that will help me achieve my fitness goals."

[evidence_required]
9 = 0
10 = 4
11 = 0
12 = 0
default = 1
