code = "PE.3.1"
competency_code = "PE.3"
descriptor = "Improve movement performance"
statement = "Apply knowledge of skill-related fitness (agility, balance, coordination, power, reaction time, speed) to movement performance and overall health."

[evidence_required]
9 = 0
10 = 4
11 = 0
12 = 0
default = 1
