code = "SS.1.3"
competency_code = "SS.1"
descriptor = "Analyze historical sources"
statement = "How well can I analyze historical sources?"

[evidence_required]
9 = 2
10 = 3
11 = 4
12 = 2
default = 1
