code = "SS.1.2"
competency_code = "SS.1"
descriptor = "Analyze multiple perspectives"
statement = "How well can I analyze factors that shaped perspectives of people in the past?"

[evidence_required]
9 = 2
10 = 3
11 = 4
12 = 2
default = 1
