code = "SS.1"
competency_area_code = "SS"
descriptor = "Analyzing Historical Events"
statement = "I can apply historical literacy to demonstrate knowledge of major eras, enduring themes, turning points, and historic influences in the modern world."
