code = "SS.2"
competency_area_code = "SS"
descriptor = "Engaging as a Citizen"
statement = "I can translate ideas, concerns, and findings into appropriate and responsible individual or collective action to improve conditions."
