code = "SS.3"
competency_area_code = "SS"
descriptor = "Understand Geographic Representations"
statement = "I can use geographic representations to analyze relationships between place, culture, politics, and economics."
