code = "SS.4"
competency_area_code = "SS"
descriptor = "Analyze Human-Environmental Interactions"
statement = "I can evaluate human-environmental interactions and use evidence to explain their impacts."
