code = "HW.3.1"
competency_code = "HW.3"
descriptor = "Demonstrate effective communication skills to promote health"
statement = "How well can I use effective communication skills to promote health?"

[evidence_required]
9 = 0
10 = 2
11 = 0
12 = 0
default = 1
