code = "HW.3.3"
competency_code = "HW.3"
descriptor = "Enhance personal health through positive decision-making"
statement = "How well can I enhance my health through positive decision-making?"

[evidence_required]
9 = 0
10 = 2
11 = 0
12 = 0
default = 1
