code = "MS.HSA-REI.D.11"
competency_code = "MS.HSA"
descriptor = "REI.D.11 Represent and solve equations and inequalities graphically"
statement = "Explain why the x-coordinates of the points where the graphs of the equations y = f(x) and y = g(x) intersect are the solutions of the equation f(x) = g(x); find the solutions approximately, e.g., using technology to graph the functions, make tables of values, or find successive approximations. Include cases where f(x) and/or g(x) are linear, polynomial, rational, absolute value, exponential, and logarithmic functions.*"

[evidence_required]
9 = 1
10 = 3
11 = 0
12 = 0
default = 1
