code = "MS.HSA-REI.D.10"
competency_code = "MS.HSA"
descriptor = "REI.D.10 Represent and solve equations and inequalities graphically"
statement = "Understand that the graph of an equation in two variables is the set of all its solutions plotted in the coordinate plane, often forming a curve (which could be a line)."

[evidence_required]
9 = 1
10 = 0
11 = 0
12 = 0
default = 1
