code = "MS.HSA-REI.D.12"
competency_code = "MS.HSA"
descriptor = "REI.D.12 Represent and solve equations and inequalities graphically"
statement = "Graph the solutions to a linear inequality in two variables as a half-plane (excluding the boundary in the case of a strict inequality), and graph the solution set to a system of linear inequalities in two variables as the intersection of the corresponding half-planes."

[evidence_required]
9 = 1
10 = 0
11 = 0
12 = 0
default = 1
