code = "MS.HSA-APR.D.7"
competency_code = "MS.HSA"
descriptor = "APR.D.7 Rewrite rational expressions"
statement = "Understand that rational expressions form a system analogous to the rational numbers, closed under addition, subtraction, multiplication, and division by a nonzero rational expression; add, subtract, multiply, and divide rational expressions."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
