code = "MS.HSA-SSE.A.1.B"
competency_code = "MS.HSA"
descriptor = "SSE.A.1.B Interpret the structure of expressions"
statement = "Interpret complicated expressions by viewing one or more of their parts as a single entity. For example, interpret P(1+r)^n as the product of P and a factor not depending on P."

[evidence_required]
9 = 2
10 = 0
11 = 0
12 = 0
default = 1
