code = "MS.HSA-REI.C.8"
competency_code = "MS.HSA"
descriptor = "REI.C.8 Solve systems of equations"
statement = "Represent a system of linear equations as a single matrix equation in a vector variable."

[evidence_required]
9 = 0
10 = 0
11 = 0
12 = 0
default = 1
