code = "MS.HSA-APR.D.6"
competency_code = "MS.HSA"
descriptor = "APR.D.6 Rewrite rational expressions"
statement = "Rewrite simple rational expressions in different forms; write a(x)/b(x) in the form q(x) + r(x)/b(x), where a(x), b(x), q(x), and r(x) are polynomials with the degree of r(x) less than the degree of b(x), using inspection, long division, or, for the more complicated examples, a computer algebra system."

[evidence_required]
9 = 0
10 = 1
11 = 0
12 = 0
default = 1
