code = "MS.HSA-SSE.A.2"
competency_code = "MS.HSA"
descriptor = "SSE.A.2 Interpret the structure of expressions"
statement = "Use the structure of an expression to identify ways to rewrite it. For example, see x^4 - y^4 as (x^2)^2 - (y^2)^2, thus recognizing it as a difference of squares that can be factored as (x^2 - y^2)(x^2 + y^2)."

[evidence_required]
9 = 4
10 = 0
11 = 0
12 = 0
default = 1
