code = "MS.HSA-APR.B.3"
competency_code = "MS.HSA"
descriptor = "APR.B.3 Understand the relationship between zeros and factors of polynomials"
statement = "Identify zeros of polynomials when suitable factorizations are available, and use the zeros to construct a rough graph of the function defined by the polynomial."

[evidence_required]
9 = 0
10 = 1
11 = 0
12 = 0
default = 1
