code = "MS.HSA-CED.A.2"
competency_code = "MS.HSA"
descriptor = "CED.A.2 Create equations that describe numbers or relationships"
statement = "Create equations in two or more variables to represent relationships between quantities; graph equations on coordinate axes with labels and scales.*"

[evidence_required]
9 = 5
10 = 2
11 = 0
12 = 0
default = 1
