code = "SCI.3.3"
competency_code = "SCI.3"
descriptor = "Evaluate and refine models"
statement = "How well can I use my understanding of the limitations of the model to make it better?"

[evidence_required]
9 = 1
10 = 1
11 = 2
12 = 1
default = 1
