code = "HOS.3"
competency_area_code = "HOS"
descriptor = "Building Networks"
statement = "I can build relationships with diverse individuals and expand my network of people who can help and support me."
