code = "HOS.2"
competency_area_code = "HOS"
descriptor = "Planning My Journey"
statement = "I can monitor my progress, set and track my goals, and create a post-secondary plan to ensure that I am college and career ready.\t\t\t\t\t\t\t\t\t\t\t"
