code = "HOS.4"
competency_area_code = "HOS"
descriptor = "Professionalism"
statement = "I can adhere to professional norms, effectively communicate and adapt to change in a variety of professional settings."
