code = "NGE.2"
competency_area_code = "NGE"
descriptor = "Presentation"
statement = "I can give purposeful and effective presentations in formal settings, making strategic and appropriate decisions about content, language use, and style based on the audience, venue, and topic."
