code = "NGE.4"
competency_area_code = "NGE"
descriptor = "Written Communication in the Workplace"
statement = "I can effectively use a variety of formats for written communication in the workplace (e.g. email, memo, business plan, technical report, press release, white paper, guides, handbooks, directions, agendas, meeting minutes, blogs (sharing/reflection), reviews, discussion boards/forum, etc.)."
