code = "ELA.3"
competency_area_code = "ELA"
descriptor = "Writing Evidence-based Arguments"
statement = "I can write evidence-based arguments to support claims in an analysis of substantive topics or texts using valid reasoning and relevant and sufficient evidence."
