code = "ELA.5"
competency_area_code = "ELA"
descriptor = "Writing Narrative Texts"
statement = "I can write narratives to develop real or imagined experiences or events using effective technique, well-chosen details and well-structured event sequences."
