code = "ELA.6"
competency_area_code = "ELA"
descriptor = "Collaborative Discussion"
statement = "I can participate in collaborative discussions, listen critically, and respond appropriately individually or in a group setting."
