code = "ELA.4"
competency_area_code = "ELA"
descriptor = "Writing Informational Texts"
statement = "I can write informative texts to examine and convey complex ideas and information clearly and accurately through the effective selection, organization, and analysis of content."
