code = "ELA.2"
competency_area_code = "ELA"
descriptor = "Expressing Ideas"
statement = "I can clearly and effectively express my ideas (in written and oral form) for particular purposes and audiences, using diverse formats and settings to inform, persuade, and connect with others."
