code = "ELA.1"
competency_area_code = "ELA"
descriptor = "Reading Critically"
statement = "I can read and critique diverse texts (e.g., books, films, advertising, music, social media, news websites)."
