code = "ELA.7"
competency_area_code = "ELA"
descriptor = "Conducting Research"
statement = "I can frame and advance an inquiry to investigate topics, build knowledge, and analyze and integrate information."
