code = "NGE.2.5"
competency_code = "NGE.2"
descriptor = "Use language and body movement effectively"
statement = "How well do I use my words, voice and body language to engage my audience?"

[evidence_required]
9 = 1
10 = 2
11 = 2
12 = 2
default = 1
