code = "WF.1"
competency_area_code = "WF"
descriptor = "Wayfinding 1"
statement = "During my first portfolio of Wayfinding, I will learn about my strengths and interests as I complete studios, exhibit my learning, and engage with my PLP."
