code = "WF.2"
competency_area_code = "WF"
descriptor = "Wayfinding 2"
statement = "During my second portfolio of Wayfinding, I will participate in career-connected studios and prepare for my Foundations Capstone."
