code = "WF.3"
competency_area_code = "WF"
descriptor = "Wayfinding 3"
statement = "During my third portfolio of Wayfinding, I will start to personalize my pathway and begin to create my post-secondary plan."
