code = "WF.4"
competency_area_code = "WF"
descriptor = "Wayfinding 4"
statement = "In my final Wayfinding portfolio, I will create my post-secondary plan and choose a passion project for my Design Capstone."
