code = "ELA.4.4"
competency_code = "ELA.4"
descriptor = "Use a formal style, objective tone, and advanced vocabulary"
statement = "How well do I use vocabulary and maintain a formal style and objective tone?"

[evidence_required]
9 = 1
10 = 1
11 = 2
12 = 2
default = 1
