code = "ELA.4.3"
competency_code = "ELA.4"
descriptor = "Use words and transitions to create cohesion"
statement = "How well do I use words and transitions to create cohesion?"

[evidence_required]
9 = 1
10 = 1
11 = 2
12 = 2
default = 1
