code = "HW.2.2"
competency_code = "HW.2"
descriptor = "Demonstrate healthy practices and behaviors"
statement = "How well do I demonstrate healthy practices and behaviors?"

[evidence_required]
9 = 0
10 = 2
11 = 0
12 = 0
default = 1
