code = "HW.2.4"
competency_code = "HW.2"
descriptor = "Evaluate the impact of cultural norms, public policy, and government regulation impact health"
statement = "How do I make sense of the impact of cultural norms, public policy, and government regulation on health?"

[evidence_required]
9 = 0
10 = 2
11 = 0
12 = 0
default = 1
