code = "MATH.1.3"
competency_code = "MATH.1"
descriptor = "Choose and apply strategies"
statement = "How well can I choose and apply one or more problem solving strategies?"

[evidence_required]
9 = 4
10 = 4
11 = 4
12 = 4
default = 1
