code = "ELA.2.4"
competency_code = "ELA.2"
descriptor = "Finalize, practice and/or prepare"
statement = "How well do I practice and prepare?"

[evidence_required]
9 = 4
10 = 4
11 = 3
12 = 2
default = 1
