code = "PE.1.2"
competency_code = "PE.1"
descriptor = "Develop and implement a fitness plan"
statement = "I can develop and implement a personal fitness plan, from established goals, that applies  principles of fitness and training."

[evidence_required]
9 = 0
10 = 4
11 = 0
12 = 0
default = 1
