code = "WF.3.4"
competency_code = "WF.3"
descriptor = "Elective Studios"
statement = "I can meet the expectations within elective studios as I explore different career fields."

[evidence_required]
9 = 0
10 = 0
11 = 4
12 = 0
default = 1
