code = "WF.3.1"
competency_code = "WF.3"
descriptor = "Resume"
statement = "I can create a professional resume and/or LinkedIn Profile that highlights my experiences, skills, and achievements."

[evidence_required]
9 = 0
10 = 0
11 = 1
12 = 0
default = 1
