code = "WF.3.7"
competency_code = "WF.3"
descriptor = "Presentation of Learning"
statement = "I can reflect on and present my learning to a panel of adults and peers."

[evidence_required]
9 = 0
10 = 0
11 = 1
12 = 0
default = 1
