code = "WF.3.5"
competency_code = "WF.3"
descriptor = "Portfolio"
statement = "I can document my best work, academic growth, and personal growth in a digital portfolio."

[evidence_required]
9 = 0
10 = 0
11 = 1
12 = 0
default = 1
