code = "WF.1.1"
competency_code = "WF.1"
descriptor = "Career Interest and Strength Finding Surveys"
statement = "I can complete the career interest and strength finding surveys in my PLP and reflect on my results."

[evidence_required]
9 = 1
10 = 0
11 = 0
12 = 0
default = 1
