code = "WF.1.5"
competency_code = "WF.1"
descriptor = "Portfolio"
statement = "I can document my best work, academic growth, and personal growth in a digital portfolio."

[evidence_required]
9 = 1
10 = 0
11 = 0
12 = 0
default = 1
