code = "WF.1.3"
competency_code = "WF.1"
descriptor = "Celebration of Learning"
statement = "I willingly participate in Celebration of Learning events by exhibiting my learning as well as artifacts I create."

[evidence_required]
9 = 1
10 = 0
11 = 0
12 = 0
default = 1
