code = "ELA.5.3"
competency_code = "ELA.5"
descriptor = "Use words and phrases, details, and sensory language"
statement = 'How well do I use words to "paint a picture" for my audience?'

[evidence_required]
9 = 0
10 = 1
11 = 1
12 = 1
default = 1
