code = "ELA.5.2"
competency_code = "ELA.5"
descriptor = "Develop the story and characters"
statement = "How well do I develop my story and characters?"

[evidence_required]
9 = 0
10 = 1
11 = 1
12 = 1
default = 1
