code = "ELA.5.6"
competency_code = "ELA.5"
descriptor = "Strengthen writing through revision"
statement = "How well do I strengthen my writing through a revision process?"

[evidence_required]
9 = 0
10 = 1
11 = 1
12 = 1
default = 1
