code = "NGE.1.5"
competency_code = "NGE.1"
descriptor = "Reflect on my work and my impact"
statement = "How well do I reflect on my work and on my impact?"

[evidence_required]
9 = 1
10 = 3
11 = 4
12 = 4
default = 1
