code = "NGE.1.2"
competency_code = "NGE.1"
descriptor = "Create a high quality project"
statement = "How well do I follow guidelines to create a high quality product?"

[evidence_required]
9 = 1
10 = 3
11 = 4
12 = 4
default = 1
